/* ================== */
/*       REGISTER     */
/* ================== */

export const REGISTER_EMPLOYEE          = "REGISTER_EMPLOYEE"
export const REGISTER_EMPLOYEE_SUCCESS  = "REGISTER_EMPLOYEE_SUCCESS"
export const REGISTER_EMPLOYEE_FAILURE  = "REGISTER_EMPLOYEE_FAILURE"



/* ================== */
 /*       LOGIN     */
/* ================== */
export const LOGIN_EMPLOYEE          = "LOGIN_EMPLOYEE"
export const LOGIN_EMPLOYEE_SUCCESS  = "LOGIN_EMPLOYEE_SUCCESS"
export const LOGIN_EMPLOYEE_FAILURE  = "LOGIN_EMPLOYEE_FAILURE"


/* ================== */
/*     EMPLOYEE        */
/* ================== */
export const FIND_ALL_EMPLOYEE          = "FIND_ALL_EMPLOYEE"
export const FIND_ALL_EMPLOYEE_SUCCESS  = "FIND_ALL_EMPLOYEE_SUCCESS"
export const FIND_ALL_EMPLOYEE_FAILURE  = "FIND_ALL_EMPLOYEE_FAILURE"

export const FIND_EMPLOYEE_BY_ID = "FIND_ EMPLOYEE_BY_ID"
export const FIND_EMPLOYEE_BY_ID_SUCCESS  = "FIND_EMPLOYEE_BY_ID_SUCCESS"
export const FIND_EMPLOYEE_BY_ID_FAILURE  = "FIND_EMPLOYEE_BY_ID_FAILURE"

export const SAVE_EMPLOYEE          = "SAVE_EMPLOYEE"
export const SAVE_EMPLOYEE_SUCCESS  = "SAVE_EMPLOYEE_SUCCESS"
export const SAVE_EMPLOYEE_FAILURE  = "SAVE_EMPLOYEE_FAILURE"

export const UPDATE_EMPLOYEE          = "UPDATE_EMPLOYEE"
export const UPDATE_EMPLOYEE_SUCCESS  = "UPDATE_EMPLOYEE_SUCCESS"
export const UPDATE_EMPLOYEE_FAILURE  = "UPDATE_EMPLOYEE_FAILURE"



